### ISSUE TITLE
Document all environment variables

### ISSUE THREAD

**Issue by pwaring** [pwaring/gcc-cross-compiler#10]
Document all the environment variables in README, and also change them into command-line arguments.

**Comment by thijstriemstra** [comment]
Porting it to Python would be really nice ;)

**Comment by pwaring** [comment]
How do you mean? Ultimately the script is running `configure && make && make install` for a bunch of packages, so a Python version would just include lots of `subprocess.call()` requests (I think).

**Comment by thijstriemstra** [comment]
I guess so, I was thinking about unit tests but I guess it's fine as it is.
