### ISSUE TITLE
Verify package downloaded completely

### ISSUE THREAD

**Issue by thijstriemstra** [pwaring/gcc-cross-compiler#8]
When you stop the build process during the download phase and later try again it will not resume the download and leave you with e.g. a kernel tarball of 500k. I guess you could use the wget `--continue` option or check a hash..

**Comment by pwaring** [comment]
Thanks for the suggestion. I'll have to think about how best to fix this - hashes are one possibility but not all packages offer them.

**Comment by pwaring** [comment]
I've added support for downloading the GNU GPG keyring and verifying the binutils tarball in 216c50adf3d9f3d6ae7b35337c8a0b071c65f90f

I'll leave this up for a while and if there is positive feedback (or no negative comments :)) I'll add the same checking for the other files.
